---
- id: 1
  name: "Квест НЛО"
  questionsList:
    - "Ты потерял память. Принять вызов НЛО?"
    - "Ты принял вызов. Поднимаемся на мостик к капитану?"
    - "Ты поднялся на мостик. Ты кто?"
    - ""